before:
  hooks:
    - go mod download

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'

release:
  disable: false

sboms:
  -
    artifacts: archive

builds:
  -
    id: cli
    dir: ./cmd/
    env: [CGO_ENABLED=0]
    ldflags: [-w -s -extldflags "-static"]
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    binary: dnstwist

archives:
  -
    name_template: "inti_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    replacements:
      darwin: macos
      linux: linux
      windows: windows
      amd64: x86_64
