name: test
on: pull_request

jobs:
  test:
    name: go
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      id: vars
      run: |
        goVersion=$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
        echo ::set-output name=go_version::${goVersion}
        echo "Using Go version ${goVersion}"
    -
      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    -
      name: Set up Go
      uses: actions/setup-go@v4
    -
      name: Download Go modules
      run: go mod download
    -
      name: Run Tests
      run: go test -v ./...
